### ISSUE TITLE
Leaflet.Gigapan WORKS!!! brillant work :)

### ISSUE THREAD

**Issue by govpack** [namrehs/Leaflet.Gigapan#1]
Leaflet.Gigapan WORKS!!! brilliant work :)

this is a non issue for me, more of an issue by way of a compliment
Leaflet.Gigapan works and is pretty nifty.

while its in my browser, the version of leaflet matters

leaflet-0.7.3 ~ WORKS!!!

leaflet-1.0.0-b1 ~ introduces some breaking changes here...

(x) Uncaught TypeError: this._getTile is not a function  L.TileLayer.Gigapan.js:79

``` javascript
_addTile: function (tilePoint, container) {
        var tilePos = this._getTilePos(tilePoint),
            tile = this._getTile(),
            zoom = this._map.getZoom(),
            imageSize = this._imageSize[zoom],
            gridSize = this._gridSize[zoom],
            tileSize = this.options.tileSize;

```

**Comment by namrehs** [comment]
Thanks for letting me know! I'm glad you're getting some use out of this.

Looks like a few API changes between 0.7.3. and 1.0.0-b1. Leaflet.Gigapan is almost entirely based on Leaflet.Zoomify (so, please don't give me too much credit - most credit goes to the author of that plugin), which has the same issue with 1.0.0-b1.

I'm not sure if my skill set is up to the task, but I'll try to fix it when I have time in the coming weeks.

If you want to take a crack at it, please do!

**Comment by govpack** [comment]
no worries, if they want to change their api then there will be a standard fix
and people more familiar than i to apply such, i'm happy with things as they are
