### ISSUE TITLE
 404 (Not Found)

### ISSUE THREAD

**Issue by AmirHome** [namrehs/Leaflet.Gigapan#2]
http://localhost/Leaflet.Gigapan/leaflet.css 404 (Not Found)
http://localhost/Leaflet.Gigapan/leaflet.js 404 (Not Found)

**Comment by namrehs** [comment]
Looks like a local configuration issue. Maybe "localhost" should be replaced with the path or host name?

Please not that this Leaflet plugin has not been updated for 3 years. It does not work with the current version of Leaflet. You are welcome to fork the repository to modify as you require.
